colorapp/urls.py
from django.urls import path

from .views import *

app_name = 'colorapp'

urlpatterns = [
    path("list", meyve_view, name="meyve_view"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

from main.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_view, name="home"),
    path("list/", list_view, name="list"),
    path("create/", create_view, name="create"),
    path("update/<int:id>", update_view, name="update"),
    path("delete/<int:id>", delete_view, name="delete"),
    path("detail/<int:id>", detail_view, name="detail"),
    path("meyve/", include("colorapp.urls"))
]

colorapp/models.py
from django.db import models

class Color(models.Model):
    name = models.CharField(max_length=50, unique=True)
    color = models.CharField(max_length=7) 
    
    def __str__(self):
        return self.name


class Meyve(models.Model):
    name = models.CharField(max_length=50)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main/models.py
from django.db import models
from .validators import validate_timestamp,validate_content
# Create your models here.


class Article(models.Model):
    author = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, verbose_name="Author"
    )
    title = models.CharField(max_length=50, verbose_name="Title")
    content = models.TextField(verbose_name="Content",validators=[validate_content])
    
    timestamp = models.DateField(blank=True, null=True,validators=[validate_timestamp])

    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date",editable=False)
    
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} | id >> {self.id}"
    
    
def upload_to(instance, filename):
    return f"products/{instance.product.name}/{filename}"

main/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    timestamp = forms.CharField(widget= forms.DateInput(attrs= {"type": "date"}))
    class Meta:
        model = Article
        fields = '__all__'
        # exlude = ('author') Olmamasini istediyin fieldin secimi
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class":"form-control"})
    # init metodundan istifade ederek butun fieldlerimi bootsrapdan istifade ederek daha duzgun gozel hala saliram
        
        
    def clean(self):
        print(self.cleaned_data)
        return super().clean()

colorapp/views.py
from django.shortcuts import render
# views.py
from .models import Meyve, Color


def meyve_view(request):
    name = request.GET.get('name')
    color = request.GET.get('color')
    
    meyveler = Meyve.objects.all()
    
    if name:
        meyveler = meyveler.filter(name__icontains=name)
    
    if color:
        meyveler = meyveler.filter(color__name=color)
    
    context = {
        'meyveler': meyveler,
        'colors': Color.objects.all()  # Tüm renkleri al
    }
    
    return render(request, 'meyve.html', context)

main/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ArticleForm
from .models import Article
# Create your views here.

from functools import wraps
from django.shortcuts import render

def my_message(view_func):
    @wraps(view_func)
    def wrapper(request, *args, **kwargs):
        # Additional decorator logic or processing can be added here
        message = "Hello, World!"
        context = {
            'message': message
        }
        return render(request, 'index.html', context)
    
    return wrapper

@my_message
def home_view(request):
    pass


def list_view(request):
    context = {
        "articles" : Article.objects.all(),
    }
    return render(request, 'list.html', context)



def create_view(request):
    form = ArticleForm
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect("list")
        
                
        else: 
            print(form.errors)
    
    context={
        'form': form,
    }
    return render(request, 'create.html',context)


def update_view(request,id):
    product = get_object_or_404(Article,id=id)
    form = ArticleForm(instance=product)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=product)
        
        if form.is_valid():
            form.save()
            
            return redirect("list")

    
    context={
        'form': form,
    }
    return render(request, 'create.html',context)


def detail_view(request,id):
    context = {
        "article" : Article.objects.get(id=id)
    }
    return render(request, 'detail.html', context)


def delete_view(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    return redirect('list')

templates/base.html
{% include 'header.html' %}

{% block body %}
    
{% endblock body %}
    
{% include 'footer.html' %}

templates/create.html
{% extends 'base.html' %}


{% block body %}

<center>
    <div class="error_message">
        
        {% if form.errors %}
            
            {% for field in form %}
                
                {% for error in field.errors %}
                    <p style="background-color:rgb(224, 80, 80); color:#fff; width:50%; margin:10px; padding:10px; border-radius:4px;">{{error}} <br></p>
                {% endfor %}
                    
            {% endfor %}
                
        {% endif %}
            
    </div>
</center>
<center>
    <form style="margin:40px;" class="w-50" method="POST">
        {% csrf_token %}
        
        {% for field in form %}
            <div class="form-group">
                <label for="">{{field.label}}: </label>
                {{field}}
            </div> 
        {% endfor %}
            
    
        <button class="btn btn-success">Submit</button>
    
    </form>
</center>
{% endblock body %}
    

templates/detail.html
{% extends 'base.html' %}


{% block body %}
<p>Author: {{article.author}}</p>
<p>Title: {{article.title}}</p>
<p>Content: {{article.content}}</p>
<a href="{% url 'delete' article.id %}">Delete</a>
<a href="{% url 'update' article.id %}">Update</a>
<hr>
{% endblock body %}

templates/footer.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
</body>

</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'list' %}">Meqalelerimiz</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create' %}">Meqale Elave Et</a>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li> -->
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

templates/index.html
{% extends 'base.html' %}

{% block body %}

<center>
    <h1>Home Page</h1>
    <p>{{ message }}</p>
    <h2>{{message_two}}</h2>
</center>

{% endblock body %}

templates/list.html
{% extends 'base.html' %}


{% block body %}

{% for article in articles %}
<p>Author: {{article.author}}</p>
<p><a href="{% url 'detail' article.id %}">Title: {{article.title}}</a></p>
<a href="{% url 'delete' article.id %}">Delete</a>
<a href="{% url 'update' article.id %}">Update</a>
<hr>
{% endfor %}

{% endblock body %}

templates/meyve.html
{% extends 'base.html' %}


{% block body %}
<style>
    .color-box {
        width: 50px;
        height: 50px;
        margin-right: 10px;
    }
</style>

<form action="{% url 'colorapp:meyve_view' %}" method="GET">
    <label for="name-input">Name:</label>
    <input type="text" id="name-input" name="name">

    <label for="color-input">Color:</label>
    <select id="color-input" name="color">
        <option value="">All Colors</option>
        
        {% for color in colors %}
            <option value="{{ color.name }}">{{ color.name }}</option>
        {% endfor %}
    </select>

    <button type="submit">Filter</button>
</form>

{% for meyve in meyveler %}
    <div>
        <span>{{ meyve.name }}</span>
        <div class="color-box" style="background-color: {{ meyve.color.color }};"></div>
    </div>
{% empty %}
    <p>No filtered results found.</p>
{% endfor %}

{% endblock body %}

templates/update.html
{% extends 'base.html' %}


{% block body %}
<style>
    form {
        transform: translate(50%, 0%);
    }

    input {
        margin-bottom: 20px;
    }
</style>
<form style="margin:40px;" class="w-50" method="POST">
    {% csrf_token %}
    
    {% for field in form %}
        <div class="form-group">
            <label for="">{{field.label}}: </label>
            {{field}}
        </div> 
    {% endfor %}
        

    <button class="btn btn-success">Submit</button>

</form>
{% endblock body %}
    